# Generated by Django 3.1.3 on 2020-11-30 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20, verbose_name='Task Name')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_reviewed', models.DateTimeField(auto_now=True, verbose_name='Last Reviewed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('1', 'High'), ('2', 'Moderate'), ('3', 'Low')], max_length=9)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagement.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_info', models.CharField(max_length=200, verbose_name='Update Information')),
                ('status', models.CharField(choices=[('1', 'Not Started'), ('2', 'In Progress'), ('3', 'Deferred'), ('4', 'Waiting on someone else'), ('5', 'Completed')], default=1, max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taskdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagement.taskdetail')),
            ],
        ),
    ]
