# Generated by Django 3.1.3 on 2020-12-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201202_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default=None, upload_to='logos'),
        ),
    ]
